[package]
name = "amd64"
version = "0.1.0"
authors = ["VisualDevelopment"]
publish = false
edition = "2021"

[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"

[dependencies]
modular-bitfield = "0.11.2"
bit = "0.1.1"
