unstable_features = true
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
force_multiline_blocks = true
format_code_in_doc_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
